#!/bin/bash
#SBATCH -A berzelius-2025-399
#SBATCH -N 1
#SBATCH --gpus 4
#SBATCH -t 00:20:00


source ~/.bashrc

conda activate dlm

echo "START TIME: $(date)"

# sh eval_gsm8k.sh
sh eval_humaneval.sh

echo "END TIME: $(date)"
